version: '3'
services:
  ui:
    build: ./ui
    ports:
      - "3001:3000"
    volumes:
      - ./ui:/ui
    links:
      - api
  api:
    build: ./backend
    ports:
      - "2000:2001"
    volumes:
      - ./backend:/backend
    links:
      - gekko
      - mysql
  mysql:
    restart: always
    build: ./db/mysql
    environment:
      MYSQL_USER: crypto
      MYSQL_PASSWORD: 123
      MYSQL_ROOT_PASSWORD: 123
    ports:
      - "3306:3306"
#    volumes:
#      - ./db/mysql/schema/config.sql:/docker-entrypoint-initdb.d/002-config.sql:rw
  mongo:
    restart: always
    build: ./db/mongo
    ports:
      - "27017:27017"
  gekko:
    restart: always
    build: ./gekko
    volumes:
      - ./gekko/volumes/gekko/history:/usr/src/app/history
      - ./gekko/config.js:/usr/src/app/config.js
    links:
      - redis
      - mysql
    environment:
      HOST: crypto
      PORT: 3000
      MYSQL: crypto_db
    ports:
     - "3000:3000"
## optionally set nginx vars if you wish to frontend it with nginx
#    environment:
#     - VIRTUAL_HOST=gekko
#     - PORT=3000
#     - DOMAIN=gekko

  redis:
    image: redis:latest
    volumes:
      - ./volumes/redis:/data