version: '3'
services:
  ui:
    build: ./ui
    ports:
    - "3001:3000"
    volumes:
    - ./ui:/ui
    links:
    - api
  api:
    build: ./backend
    ports:
    - "2000:2001"
    volumes:
    - ./backend:/backend
    links:
    - gekko
    - mysql
  gekko:
    build: ./gekko
    ports:
    - "3000:3000"
    volumes:
    - ./gekko:/gekko
    links:
    - mysql
  mysql:
    build: ./db
    ports:
    - "1433:1433"