version: '2.2'
services:
  ui:
    build: ./ui
    ports:
      - "3001:3000"
    volumes:
      - ./ui:/usr/src/app
    links:
      - api
  api:
    build: ./backend
    ports:
      - "8000:3000"
    volumes:
      - ./backend:/usr/src/app
    links:
      - mysql
  test-runner:
    build: 
      context: ./test-runner
      args:
        - TEST_ASSET
        - TEST_CURRENCY
        - TEST_EXCHANGE
        - TEST_TIME
    environment:
      - MYSQL_HOST=crypto_db
      - MYSQL_USER=crypto
      - MYSQL_PASSWORD=y9TxJd8LFmWFZ58p
      - GEKKO_HOST=gekko
      - GEKKO_PORT=3000
    volumes:
      - ./test-runner:/usr/src/app:rw
    links:
#      - mysql #disabled because there's no need to run it locally when pointing multiple machines to a single db
      - gekko
  mysql:
    restart: always
    build: ./db/mysql
    environment:
      - MYSQL_USER=crypto
      - MYSQL_PASSWORD=y9TxJd8LFmWFZ58p
      - MYSQL_ROOT_PASSWORD=123
    ports:
      - "3306:3306"
    volumes:
      - ./db/mysql/schema/config.sql:/docker-entrypoint-initdb.d/000.sql
      - ./db/mysql/schema/createTables.sql:/docker-entrypoint-initdb.d/001.sql
      - ./db/mysql/schema/addBaseData.sql:/docker-entrypoint-initdb.d/002.sql
      - ./db/mysql/data:/var/lib/mysql:rw
    healthcheck:
      test: ["CMD", "mysql", "-u", "crypto", "backtests", "-e", "SELECT * FROM trade_types"]
      interval: 5s
      retries: 8
#  mongo:
#    restart: always
#    build: ./db/mongo
#    ports:
#      - "27017:27017"
  gekko:
    # restart: always
    build: ./gekko
    volumes:
      # - ./gekko:/usr/src/app:rw
      # - ./gekko/volumes/gekko/history:/usr/src/app/history
      - ./gekko/history:/usr/src/app/history:rw
      - ./gekko/config.js:/usr/src/app/config.js
      - ./gekko/core:/usr/src/app/core:rw
      - ./gekko/web/vue/src:/usr/src/app/web/vue/src:rw
      - ./gekko/web/vue/dist:/usr/src/app/web/vue/dist:rw
      - ./gekko/strategies:/usr/src/app/strategies:rw
      - ./gekko/plugins:/usr/src/app/plugins:rw
      # - ./gekko/node_modules:/usr/src/app/node_modules:rw
      # - ./gekko/core:/usr/src/app/core:rw
    links:
      - redis
    environment:
      - HOST=localhost
      - PORT=3000
    ports:
     - "3000:3000"
    cpus: 0.7
## optionally set nginx vars if you wish to frontend it with nginx
#    environment:
#     - VIRTUAL_HOST=gekko
#     - PORT=3000
#     - DOMAIN=gekko
  redis:
    image: redis:latest
    volumes:
      - ./gekko/volumes/redis:/data
